# Generated by Django 3.2.9 on 2021-11-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211111_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='C:\\Users\\Beko\\Desktop\\API_mini_market\\mini_shop_api\\default/photo/default_product_img.png', upload_to='photos/%Y/%m/%d'),
        ),
    ]
