# Generated by Django 3.2.9 on 2021-11-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='C:\\Users\\Beko\\Desktop\\API_mini_market\\mini_shop_api\\default/photo/default_product_img.png', upload_to='media/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='stars',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
